In [1]:
import pandas as pd
import numpy as np

In [2]:
csv_path = "/Users/ishigurofutoshi/lab_materials/data/integrated_route.csv"
df = pd.read_csv(csv_path,index_col=0)
df = df.dropna(axis=1)
#date_time = pd.to_datetime(df.pop("5 Minutes"),format="%Y.%m.%d %H:%M").reset_index(drop=True)
df = df.reset_index(drop=True)

In [3]:
for route in df.columns[1:]:
    print(route)
    for id in df.loc[:,route].sample(frac=0.6).index:
        df.loc[id,route] = np.nan

11750
13147
13867
14467
14987
16207
16507
16509
16510
16511
18174
18820
18822
18824
18826
18828
18830
18832
18834
18836
18838
18840
18842
18844
18846
18848
18850
18852
18854
18856
18858
18860
18862
18864
18866
18868
18870
18872
18874
19835
19837
19839
19841
19955
19957
19975
19977
19979
19981
20274
20294
20734
20735
2131
2132
2133
2134
2135
22619
22620
22622
22626
22627
22629
271
272
273
274
275
276
332
3394
357
358
359
360
361
362
363
364
365
366
367
368
369
371
372
373
374
375
376
377
378
379
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
433
434
460
4646
4647
4648
4649
4650
4651
471
472
551
571
6200
6201
6202
6203
6204
6205
6206
6207
6208
6209
6210
6211
6212
6213
6214
6215
6216
6217
6218
6219
6220
6221
6222
6223
6224
6225
6226
6227
6357
6600
6601
6602
6603
6604
6605
6606
6607
6608
6609
6612
6613
6614
6615
6616
6619
6620
6621
6622
6623
6627
6630
6631
6632
6633
6634
6636
6637
6638
6639
6640
6641
6642
6643
6644
6645
6647
6648
6649
6650
6651
6652
6653
6654
6655
6656
6657
6658
6659
6660
6661
6662
6663
6664
6665
6666
6667
6668
6669
6670
6671
6673
6674
6675
6677
6678
6679
6680
6682
6683
6684
6685
6686
6687
6688
6689
6690
6691
6692
6693
6694
6695
6696
6697
6698
6699
6700
6701
6705
6706
6707
6708
6709
6710
6711
6712
6713
6714
6716
6717
6718
6719
6720
6721
6722
6723
6724
6725
77
78
79
80
81
82
83
84
85
86
87
88

In [4]:
df

,5 Minutes,11750,13147,13867,14467,14987,16207,16507,16509,16510,...,79,80,81,82,83,84,85,86,87,88
0,2021/1/1 0:00,16.88,34.90,8.62,19.35,NaN,21.43,30.88,30.22,NaN,...,NaN,29.38,NaN,35.93,11.78,11.87,NaN,NaN,15.92,NaN
1,2021/1/1 0:05,16.97,34.87,NaN,NaN,7.00,NaN,30.87,NaN,NaN,...,30.15,29.37,36.37,NaN,11.82,11.88,16.80,16.78,NaN,12.12
2,2021/1/1 0:10,16.98,NaN,8.67,19.38,NaN,NaN,30.82,NaN,36.02,...,NaN,29.27,NaN,35.88,NaN,NaN,NaN,NaN,NaN,NaN
3,2021/1/1 0:15,16.98,35.05,NaN,NaN,NaN,21.37,30.85,30.15,NaN,...,30.15,NaN,NaN,35.98,NaN,NaN,16.82,NaN,15.83,12.18
4,2021/1/1 0:20,NaN,NaN,NaN,NaN,7.03,21.40,30.88,NaN,NaN,...,NaN,NaN,NaN,36.08,11.85,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80095,2021/7/31 3:35,NaN,35.30,8.60,19.42,NaN,NaN,NaN,NaN,NaN,...,NaN,30.08,36.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80096,2021/7/31 3:40,NaN,35.30,8.58,NaN,NaN,NaN,NaN,NaN,36.02,...,30.68,30.13,NaN,NaN,NaN,12.05,16.90,NaN,15.73,12.87
80097,2021/7/31 3:45,17.32,NaN,NaN,19.43,NaN,NaN,NaN,NaN,NaN,...,30.52,NaN,36.02,NaN,NaN,NaN,16.87,NaN,NaN,NaN
80098,2021/7/31 3:50,17.25,35.32,NaN,19.48,7.23,21.73,NaN,NaN,NaN,...,30.67,29.90,NaN,NaN,11.82,NaN,NaN,NaN,NaN,NaN
80099,2021/7/31 3:55,NaN,NaN,NaN,19.50,NaN,21.83,NaN,NaN,NaN,...,30.95,NaN,NaN,36.10,NaN,12.07,NaN,17.30,15.80,NaN

In [5]:
df.to_csv("/Users/ishigurofutoshi/lab_materials/data/integrated_route_missing60.csv")